// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfpga_convolution.h"

extern XFpga_convolution_Config XFpga_convolution_ConfigTable[];

XFpga_convolution_Config *XFpga_convolution_LookupConfig(u16 DeviceId) {
	XFpga_convolution_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFPGA_CONVOLUTION_NUM_INSTANCES; Index++) {
		if (XFpga_convolution_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFpga_convolution_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFpga_convolution_Initialize(XFpga_convolution *InstancePtr, u16 DeviceId) {
	XFpga_convolution_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFpga_convolution_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFpga_convolution_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

