// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xfpga_convolution.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XFpga_convolution_CfgInitialize(XFpga_convolution *InstancePtr, XFpga_convolution_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XFpga_convolution_Start(XFpga_convolution *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_AP_CTRL) & 0x80;
    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XFpga_convolution_IsDone(XFpga_convolution *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XFpga_convolution_IsIdle(XFpga_convolution *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XFpga_convolution_IsReady(XFpga_convolution *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XFpga_convolution_EnableAutoRestart(XFpga_convolution *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XFpga_convolution_DisableAutoRestart(XFpga_convolution *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_AP_CTRL, 0);
}

void XFpga_convolution_Set_image_r(XFpga_convolution *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_IMAGE_R_DATA, Data);
}

u32 XFpga_convolution_Get_image_r(XFpga_convolution *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_IMAGE_R_DATA);
    return Data;
}

void XFpga_convolution_Set_kernel(XFpga_convolution *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_KERNEL_DATA, Data);
}

u32 XFpga_convolution_Get_kernel(XFpga_convolution *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_KERNEL_DATA);
    return Data;
}

void XFpga_convolution_Set_output_r(XFpga_convolution *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_OUTPUT_R_DATA, Data);
}

u32 XFpga_convolution_Get_output_r(XFpga_convolution *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_OUTPUT_R_DATA);
    return Data;
}

void XFpga_convolution_InterruptGlobalEnable(XFpga_convolution *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_GIE, 1);
}

void XFpga_convolution_InterruptGlobalDisable(XFpga_convolution *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_GIE, 0);
}

void XFpga_convolution_InterruptEnable(XFpga_convolution *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_IER);
    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_IER, Register | Mask);
}

void XFpga_convolution_InterruptDisable(XFpga_convolution *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_IER);
    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_IER, Register & (~Mask));
}

void XFpga_convolution_InterruptClear(XFpga_convolution *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XFpga_convolution_WriteReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_ISR, Mask);
}

u32 XFpga_convolution_InterruptGetEnabled(XFpga_convolution *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_IER);
}

u32 XFpga_convolution_InterruptGetStatus(XFpga_convolution *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XFpga_convolution_ReadReg(InstancePtr->Axilites_BaseAddress, XFPGA_CONVOLUTION_AXILITES_ADDR_ISR);
}

